version: "3.8"

services:
    db:
        image: mariadb
        container_name: db
        restart: always
        environment:
          MARIADB_DATABASE: ${MARIADB_DATABASE:-planify}
          MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-root}
        volumes:
          - ./migrations/01-tables.sql:/docker-entrypoint-initdb.d/migration.sql
          - db_data:/var/lib/mysql
        ports:
        - "3308:3306"
        healthcheck:
          test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MARIADB_ROOT_PASSWORD:-root}"]
          interval: 5s
          timeout: 3s
          retries: 3

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: always
        environment:
          PMA_HOST: ${PMA_HOST:-db}
          PMA_PORT: ${PMA_PORT:-3306}
          PMA_USER: ${PMA_USER:-root}
          PMA_PASSWORD: ${PMA_PASSWORD:-root}
          MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-root}
          MYSQL_PASSWORD: ${MARIADB_PASSWORD:-root}
        ports:
        - "8080:80"
        depends_on:
          db:
            condition: service_healthy

    go-api:
      build:
        context: .
        dockerfile: Dockerfile
      restart: on-failure
      environment:
        MARIADB_DATABASE: ${MARIADB_DATABASE:-planify}
        MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-root}
      ports:
        - "8000:8000"
      depends_on:
        db:
          condition: service_healthy

volumes:
    db_data:
        driver: local