version: "3.8"

services:
    db:
        image: mariadb
        container_name: db
        restart: always
        environment:
          MARIADB_DATABASE: ${DB_NAME:-planify}
          MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
        volumes:
          - ./migrations/01-tables.sql:/docker-entrypoint-initdb.d/migration.sql
          - db_data:/var/lib/mysql
        ports:
        - "${DB_PORT:-3308}:3306"
        healthcheck:
          test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u${DB_USER:-root}", "-p${DB_ROOT_PASSWORD:-root}"]
          interval: 5s
          timeout: 3s
          retries: 3

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: always
        environment:
          PMA_HOST: ${DB_HOST:-db}
          PMA_PORT: ${DB_PORT:-3306}
          PMA_USER: ${DB_USER:-root}
          PMA_PASSWORD: ${DB_PASSWORD:-root}
          MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
          MYSQL_PASSWORD: ${DB_PASSWORD:-root}
        ports:
        - "8080:80"
        depends_on:
          db:
            condition: service_healthy

    go-api:
      build:
        context: .
        dockerfile: Dockerfile
      restart: on-failure
      environment:
        DB_HOST: ${DB_HOST:-planify}
        DB_NAME: ${DB_NAME:-planify}
        DB_USER: ${DB_USER:-root}
        DB_PASSWORD: ${DB_PASSWORD:-root}
        DB_PORT: ${DB_PORT:-3306}
      ports:
        - "8000:8000"
      depends_on:
        db:
          condition: service_healthy

volumes:
    db_data:
        driver: local